parameters:
    json_schema.generator.class:                                  "Knp\\JsonSchemaBundle\\Schema\\SchemaGenerator"
    json_schema.builder.class:                                    "Knp\\JsonSchemaBundle\\Schema\\SchemaBuilder"
    json_schema.reflection_factory.class:                         "Knp\\JsonSchemaBundle\\Schema\\ReflectionFactory"
    json_schema.validator.class:                                  "JsonSchema\\Validator"
    json_schema.builder.handler.form_type_guesser_handler.class:  "Knp\\JsonSchemaBundle\\Property\\FormTypeGuesserHandler"
    json_schema.builder.handler.custom_handler.class:             "Knp\\JsonSchemaBundle\\Property\\CustomHandler"

services:
    json_schema.generator:
        class: %json_schema.generator.class%
        arguments:
            - @json_schema.validator
            - @json_schema.builder
            - @json_schema.reflection_factory

    json_schema.builder:
        public: false
        class: %json_schema.builder.class%

    json_schema.reflection_factory:
        public: false
        class: %json_schema.reflection_factory.class%

    json_schema.validator:
        public: false
        class: %json_schema.validator.class%

    json_schema.builder.handler.chained_guesser:
        public: false
        class: "Knp\\JsonSchemaBundle\\Property\\FormTypeGuesserHandler"
        arguments:
            - @form.chain.guesser
        tags:
            - { name: json_schema.builder.handler, priority: 10 }

    json_schema.builder.handler.custom:
        public: false
        class: %json_schema.builder.handler.custom_handler.class%
        arguments:
            - @validator.mapping.class_metadata_factory
        tags:
            - { name: json_schema.builder.handler, priority: 0 }

    form.chain.guesser:
        public: false
        class: "Symfony\\Component\\Form\\FormTypeGuesserChain"
        arguments:
            - [@form.type_guesser.validator, @form.type_guesser.doctrine]
